VFS-11629 Reviwer's suggested fixes

diff --git a/docker/demo-mode/await-demo-oneclient b/docker/demo-mode/await-demo-oneclient
--- a/docker/demo-mode/await-demo-oneclient
+++ b/docker/demo-mode/await-demo-oneclient
@@ -1,19 +1,20 @@
 #!/bin/bash
 
-# This file is created by onezone.py when the service is ready
-SERVICE_READY_LOCK_FILE='/root/service-ready.lock'
+source /root/demo-mode/better-curl.sh
+
+ONEZONE_IP=$(getent hosts onezone.local | awk '{ print $1 }')
 
 # Optional first argument
 TIMEOUT=${1:-300}
 
 RETRY_NUM=0
-while [[ ! -f ${SERVICE_READY_LOCK_FILE} ]]; do
+while ! [ -d /mnt/oneclient/demo-space ]; do
     RETRY_NUM=$((RETRY_NUM + 1))
 
     if ! ((RETRY_NUM % 15)); then
         echo -e "\e[1;33m"
         echo "-------------------------------------------------------------------------"
-        echo "Awaiting Oneprovider service readiness..."
+        echo "Awaiting Oneclient readiness..."
         echo "-------------------------------------------------------------------------"
         echo -e "\e[0m"
     fi
@@ -21,7 +22,8 @@ while [[ ! -f ${SERVICE_READY_LOCK_FILE} ]]; do
     if [[ ${RETRY_NUM} -eq ${TIMEOUT} ]]; then
         echo -e "\e[1;31m"
         echo "-------------------------------------------------------------------------"
-        echo "ERROR: The Oneprovider service failed to initialize within ${TIMEOUT} seconds, exiting."
+        echo "ERROR: Oneclient failed to mount demo-space from oneprovider ${ONECLIENT_PROVIDER_HOST}"
+	echo "       within ${TIMEOUT} seconds, exiting."
         echo "-------------------------------------------------------------------------"
         echo -e "\e[0m"
         exit 1
